name: Build and deploy container app to Azure Web App - LukaWebApp01

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker registry (hardcoded username and password)
      uses: docker/login-action@v2
      with:
        registry: mcr.microsoft.com
        username: 'etozheluka1'  # Replace with your Docker registry username
        password: 'dckr_pat_GdUDuOTXOaL538p3Q9Ifqo_jRZ8'  # Replace with your Docker registry password

    - name: Build and push container image to Azure App Service
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 'mcr.microsoft.com/your_docker_registry_username/appsvc/staticsite:${{ github.sha }}'
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App (hardcoded publish profile)
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'LukaWebApp01'
        slot-name: 'production'
        publish-profile: '<paste_your_publish_profile_here>'  # Replace with your publish profile XML content
        images: 'mcr.microsoft.com/your_docker_registry_username/appsvc/staticsite:${{ github.sha }}'
